# Generated by Django 5.2.7 on 2025-10-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('question_text', models.CharField(max_length=255)),
                ('options', models.TextField()),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
    ]
